# infrastructure/a2a_adapter.py

"""Concrete A2A Client Adapter for Structured RAG (SRAG).

This adapter connects the RAG project to the external SRAG agent via the
official Agent-to-Agent (A2A) protocol.

Architecture:
    RAG Code -> A2A Client Adapter -> HTTP/JSON-RPC (A2A) -> SRAG Server -> MCP -> PostgreSQL

This is the only module in the RAG project that interacts with the A2A SDK.
All other RAG components communicate through this adapter without any direct
coupling to MCP or PostgreSQL.
"""

import asyncio
import logging
import os
from concurrent.futures import ThreadPoolExecutor
from typing import Optional, Coroutine, Any
import httpx
from dotenv import load_dotenv

from a2a.client import A2ACardResolver, ClientConfig, create_client
from a2a.client.errors import A2AClientError, AgentCardResolutionError
from a2a.helpers import get_message_text, new_text_message
from a2a.types import AgentCard, Role, SendMessageRequest

try:
    import config
    DEFAULT_SERVER_URL = getattr(config, "SRAG_A2A_URL", "http://localhost:8001")
except ImportError:
    load_dotenv()
    DEFAULT_SERVER_URL = os.getenv("SRAG_A2A_URL", "http://localhost:8001")

logger = logging.getLogger(__name__)


class SRAGA2AAdapter:
    """A2A client adapter to send queries to the SRAG agent and receive answers."""

    def __init__(
        self,
        server_url: Optional[str] = None,
        timeout: float = 60.0,
    ) -> None:
        """Initialize adapter with the target SRAG A2A server URL.

        Args:
            server_url: Base URL of the SRAG A2A server (e.g. http://localhost:8001).
                        Defaults to SRAG_A2A_URL from config or environment.
            timeout: HTTP request timeout in seconds.
        """
        self.server_url = (server_url or os.getenv("SRAG_A2A_URL") or DEFAULT_SERVER_URL).rstrip("/")
        self.timeout = timeout
        self._cached_card: Optional[AgentCard] = None

    async def get_agent_card(self, http_client: httpx.AsyncClient) -> AgentCard:
        """Discover and cache the remote SRAG Agent Card from /.well-known/agent-card.json."""
        if self._cached_card is None:
            resolver = A2ACardResolver(http_client, self.server_url)
            self._cached_card = await resolver.get_agent_card()
            logger.info(
                "Resolved SRAG Agent Card: '%s' (v%s)",
                self._cached_card.name,
                self._cached_card.version,
            )
        return self._cached_card

    async def ask(self, query: str) -> str:
        """Send a natural-language query to the SRAG A2A agent and return the answer.

        Args:
            query: The user task or natural-language database question.

        Returns:
            The text response generated by the SRAG agent.

        Raises:
            ConnectionError: If unable to reach the SRAG A2A server.
            RuntimeError: If Agent Card resolution fails or A2A communication errors occur.
        """
        if not query or not query.strip():
            return "No query provided."

        try:
            async with httpx.AsyncClient(timeout=self.timeout) as http_client:
                # 1. Discover Agent Card
                try:
                    card = await self.get_agent_card(http_client)
                except httpx.ConnectError as e:
                    error_msg = (
                        f"Cannot connect to SRAG A2A server at {self.server_url}. "
                        "Please verify the SRAG A2A server is running on that port."
                    )
                    logger.error(error_msg)
                    raise ConnectionError(error_msg) from e
                except AgentCardResolutionError as e:
                    error_msg = f"Failed to resolve Agent Card from {self.server_url}: {e}"
                    logger.error(error_msg)
                    raise RuntimeError(error_msg) from e

                # 2. Instantiate A2A client from discovered Agent Card
                client_config = ClientConfig(httpx_client=http_client)
                client = await create_client(card, client_config=client_config)

                # 3. Create protocol-compliant SendMessageRequest
                user_msg = new_text_message(
                    text=query.strip(),
                    role=Role.ROLE_USER,
                )
                request = SendMessageRequest(message=user_msg)

                # 4. Stream response and extract final text answer
                final_answer: Optional[str] = None
                async for response in client.send_message(request):
                    if response.HasField("message"):
                        final_answer = get_message_text(response.message)
                    elif response.HasField("task"):
                        task = response.task
                        logger.debug("A2A task update: %s", task.status.state)

                if final_answer is not None:
                    return final_answer

                raise RuntimeError("SRAG A2A server returned an empty response.")

        except A2AClientError as e:
            error_msg = f"A2A client communication error: {e}"
            logger.error(error_msg)
            raise RuntimeError(error_msg) from e


async def ask_srag_agent(
    query: str,
    server_url: Optional[str] = None,
) -> str:
    """Convenience function to asynchronously query the SRAG agent over A2A.

    Usage:
        from infrastructure.a2a_adapter import ask_srag_agent
        response = await ask_srag_agent("How many employees are currently hired?")
    """
    adapter = SRAGA2AAdapter(server_url=server_url)
    return await adapter.ask(query)


def run_coroutine_sync(coro: Coroutine[Any, Any, Any]) -> Any:
    """Safely execute an async coroutine synchronously.

    Checks if an asyncio event loop is already active in the current thread
    (e.g., inside Streamlit or an async worker). If active, runs the coroutine
    in a dedicated worker thread to avoid loop collision or deadlocks.
    """
    try:
        loop = asyncio.get_running_loop()
    except RuntimeError:
        loop = None

    if loop and loop.is_running():
        with ThreadPoolExecutor(max_workers=1) as executor:
            future = executor.submit(lambda: asyncio.run(coro))
            return future.result()
    else:
        return asyncio.run(coro)


def ask_srag_database(
    query: str,
    server_url: Optional[str] = None,
) -> str:
    """Synchronously queries the remote SRAG database agent via A2A protocol.

    Args:
        query: The natural language database question.
        server_url: Optional override for the SRAG A2A server URL.

    Returns:
        The response text from the SRAG agent, or a polite error explanation
        if the remote agent is unreachable.
    """
    cleaned_query = (query or "").strip()
    if not cleaned_query:
        return "No database query provided."

    target_url = server_url or getattr(config, "SRAG_A2A_URL", "http://localhost:8001")

    try:
        return run_coroutine_sync(ask_srag_agent(cleaned_query, server_url=target_url))
    except (ConnectionError, RuntimeError, Exception) as err:
        logger.warning("SRAG A2A database invocation failed: %s", err)
        return (
            f"Unable to query the structured database: The remote SRAG agent at {target_url} "
            f"is currently unreachable ({type(err).__name__}). Please ensure the SRAG A2A server is running."
        )


__all__ = [
    "SRAGA2AAdapter",
    "ask_srag_agent",
    "ask_srag_database",
    "run_coroutine_sync",
]


if __name__ == "__main__":
    import asyncio
    import sys

    test_query = (
        " ".join(sys.argv[1:])
        if len(sys.argv) > 1
        else "How many tables are in the database? Return only the table count."
    )

    print(f"\n[RAG -> A2A Adapter] Querying SRAG A2A Server...")
    print(f"[Query] {test_query}\n")

    try:
        result = asyncio.run(ask_srag_agent(test_query))
        print("=" * 60)
        print("SRAG A2A Response:")
        print(result)
        print("=" * 60 + "\n")
    except Exception as err:
        print(f"Error: {type(err).__name__}: {err}")
